language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare

deploy:
  provider: heroku
  api_key:
    secure: bjJop0wM6VB6bQz318DeFvaxdayjDCW/YqipIsj0PNu0zA+VCbdeGfn2cJMMp6EmGJbLSftjLtuuGPakufqrEWUGuPONjRooUNr6LfJnDv+bEWAq58NQs7yUXglIn22YWvkP0Q1yg8/98ZQ6fSR3OIKFs88iVRUTS+BAwIm07mE=
  app: young-thicket-6801
  on:
    repo: hhkopper/ratebeer
  run: "rake db:migrate"
